[package]
name = "notmarioland"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = { version = "0.4.12", features = ["audio"] }
quad-snd = "0.2.8"

[profile.dev.package."*"]
opt-level = 3
